name: Build on Branch Push

on:
  push:
    branches:
      - 'main'

jobs:
  build_android_preview:
    name: Build Android App
    type: build
    params:
      platform: android
      profile: preview
